Add item in Spinner
euphony-io/soundless-check-in pull request #20
Opened 2021-08-27 04:48 UTC by JuSeongPil

thank u everyone

2021-08-27 13:17 UTC, jopopcorn requested changes
Please correct the part I reviewed. Please cheer up a little bit more!

2021-08-28 04:18 UTC, sujin9 reviewed
Good job !
Same opinion as Sooyeon :)
Also you should delete livingCity EditText later cuz we're gonna use Spinner instead right :)

2021-08-28 04:18 UTC, sujin9 commented on app/src/main/res/layout/tutorial.xml
> +        android:orientation="horizontal">
```suggestion
        android:orientation="horizontal"
        android:padding="10dp" >
```

2021-08-28 04:23 UTC, sujin9 commented on app/src/main/res/layout/tutorial.xml
> +        android:orientation="horizontal">
And one more suggestion here! 
It looks better if there's a bit of white space.

2021-08-29 02:08 UTC, JuSeongPil commented on app/src/main/res/values/array.xml
> +    </string-array>
hi, it is a array.xml file?
but i just using strings.xml file in this project! 
thank u!

2021-09-02 07:08 UTC, closed without merging